### Create user request
POST http://127.0.0.1:8080/v1/users/register HTTP/1.1
Content-Type: application/json

{
  "username": "alperenss",
  "firstname": "alperen",
  "lastname": "emin",
  "email": "alprn@hotmail.com",
  "phone": "05555555555",
  "password": "abcd123",
  "age" : 25
}

### Healthcheck request
GET {{baseUrl}}/v1/health

### Login user
POST {{baseUrl}}/v1/auth/login HTTP/1.1
Content-Type: application/json 

{
  "username": "alperenss",
  "password": "abcd123"
}

> {% client.global.set("token", response.body.token); %}

### Get All Users  - AuthRequired
GET {{baseUrl}}/v1/users
Authorization: Bearer {{token}}

